### ISSUE TITLE
utilisation du markdown

### ISSUE THREAD

**Issue by GuyliannEngels** [BioDataScience-Course/markdown-decouverte#1]
Il n'est pas si simple que cela d'oublier les habitudes prises avec des outils comme Word. 

Après avoir rapidement réalisé une visite sur les différents dépôts des étudiants de Bioinformatique et science des données , nous pouvons rapidement tirer la conclusion que certains concepts n'ont pas été compris comme par exemple les titres 

Je propose pour cet exercice de rajouter au sein du dépot les aides-mémoires liés au markdown de RStudio. 

Qu'en pensez vous ? une autre idée ?

**Comment by phgrosjean** [comment]
Ne peut-on pas simplement pointer les entrées de menu dans RStudio correspondants à ces aides-mémoires. Ainsi, les étudiants auront plus facile à les retrouver plus tard.

**Comment by GuyliannEngels** [comment]
C'est une très bonne idée. Il n'est pas nécessaire de donner directement l'aide-mémoire en pdf dans le dépôt. Il est plus intéressant de montrer comment les retrouver via 

`Help -> Cheatsheets -> ... `
